Repository wildcodeschool-2025-03/js-p3-takutaku, pull requests merged in 2025-06, with the labels that each got.

#2 AddBddLocale
  server/database/schema.sql
Labels: Add

#15 Ajout du User Context
  client/context/AnimeContext.tsx
  client/context/UserContext.tsx
Labels: Add

#23 Add_login
  client/context/UserContext.tsx
  client/package.json
  client/src/components/Header/DesktopNavBar.tsx
  client/src/components/LogIn.tsx
  client/src/components/Mobile Header/NavBar.tsx
  client/src/main.tsx
  client/src/pages/Login.tsx
  client/src/pages/Watch.tsx
  server/.env.sample
  server/package.json
  server/src/middleware/security.ts
  server/src/modules/Abonnement/abonnementAction.ts
  server/src/modules/auth/authAction.ts
  server/src/modules/auth/authRepository.ts
  server/src/router.ts
Labels: Add

#26 Bug_UserAbonnement
  client/src/components/admin/userManagement/UsersManagement.tsx
  server/src/modules/Abonnement/abonnementRepository.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: bug

#30 add component watchEpisode
  client/public/play.png
  client/src/components/watch/WatchEpisode.tsx
  client/src/pages/Watch.tsx
  server/database/schema.sql
Labels: Add

#36 S03 us01 historique
  client/context/UserContext.tsx
  client/src/components/History/HistoryComponent.tsx
  client/src/components/LogIn.tsx
  client/src/components/ProtectRoute/PrivateRoute.tsx
  client/src/main.tsx
  client/src/middleware/security.ts
  client/src/pages/History.tsx
  server/src/modules/user/userAction.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: bug, Add, Fix

#38 add_function_searchBar_home_desktop
  client/context/AnimeContext.tsx
  client/context/UserContext.tsx
  client/src/components/Header/DesktopNavBar.tsx
  client/src/components/Header/DesktopSearchBar.tsx
  client/src/components/Mobile Header/NavBar.tsx
  client/src/components/Mobile Header/SearchBar.tsx
  client/src/components/home/Carousel.tsx
  client/src/main.tsx
  client/src/pages/Anime.tsx
Labels: Add

#40 S03 us01historique 2
  client/context/UserContext.tsx
  client/src/components/History/HistoryComponent.tsx
  client/src/components/watch/WatchEpisode.tsx
  server/src/modules/user/userAction.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: MERGE CONFLIT, Fix

#42 Ajout du menu de navigation en état connecté
  client/context/UserContext.tsx
  client/public/profilepicture1.png
  client/public/profilpicture.png
  client/src/App.tsx
  client/src/components/Header/DesktopNavBar.tsx
  client/src/components/Mobile Header/NavBar.tsx
  client/src/components/UserMenu/BurgerProfil.tsx
  client/src/components/home/Carousel.tsx
  server/src/modules/auth/authAction.ts
Labels: Add, Fix

#43 Ajout animation menu burger et fix CSS
  client/src/components/Mobile Header/NavBar.tsx
  client/src/components/UserMenu/BurgerProfil.tsx
Labels: Fix

#46 Fix multibug
  client/context/UserContext.tsx
  client/src/App.tsx
  client/src/components/Header/DesktopNavBar.tsx
  client/src/components/Header/DesktopSearchBar.tsx
  client/src/components/Mobile Header/NavBar.tsx
  client/src/components/Mobile Header/SearchBar.tsx
  client/src/components/UserMenu/BurgerProfil.tsx
  client/src/components/admin/animeManegement/AnimesManagement.tsx
  client/src/components/admin/userManagement/UsersManagement.tsx
  client/src/components/home/Abonnement.tsx
  client/src/components/home/Carousel.tsx
  server/database/schema.sql
  server/src/modules/Abonnement/abonnementAction.ts
  server/src/modules/auth/authAction.ts
  server/src/router.ts
Labels: bug, Fix

#47 Bug Caroussel And Location BurgerProfil
  client/src/components/UserMenu/BurgerProfil.tsx
  client/src/components/home/Carousel.tsx
Labels: bug
