Repository wildcodeschool-2025-03/js-p3-takutaku, pull requests merged in 2025-07, with the labels that each got.

#51 Fix Login localStorage
  client/context/AuthContext.tsx
  client/src/components/Header/DesktopNavBar.tsx
Labels: Fix

#56 Add security route admin + abonnement button
  client/context/AuthContext.tsx
  client/src/components/ProtectRoute/PrivateRoute.tsx
  client/src/components/ProtectRoute/PrivateRouteAdmin.tsx
  client/src/components/home/Abonnement.tsx
  client/src/main.tsx
  server/src/modules/anime/animeRepository.ts
  server/src/modules/user/userAction.ts
Labels: Add

#58 Fix Favorite Feature
  client/src/components/History/HistoryComponent.tsx
  client/src/components/account/ProfileSettings.tsx
  client/src/components/admin/animeManegement/AnimesManagement.tsx
  client/src/components/admin/userManagement/UsersManagement.tsx
  client/src/components/favorite/FavoriteButton.tsx
  client/src/components/watch/WatchEpisode.tsx
  client/src/pages/Favorite.tsx
  server/database/schema.sql
  server/src/modules/favoriteAnime/favoriteAnimeAction.ts
  server/src/modules/favoriteAnime/favoriteAnimeRepository.ts
  server/src/modules/usersAnime/usersAnimeActions.ts
  server/src/router.ts
Labels: Fix

#60 Fix_PayementPopup_SearchBar
  client/context/AnimeContext.tsx
  client/context/AuthContext.tsx
  client/src/App.tsx
  client/src/components/Footer.tsx
  client/src/components/Header/DesktopSearchBar.tsx
  client/src/components/History/HistoryComponent.tsx
  client/src/components/LogIn.tsx
  client/src/components/account/ProfileSettings.tsx
  client/src/components/admin/animeManegement/AnimesManagement.tsx
  client/src/components/admin/userManagement/UsersManagement.tsx
  client/src/components/genre/ButtonsPageGenre.tsx
  client/src/components/genre/SearchCarousel.tsx
  client/src/components/genre/ShearchBarGenre.tsx
  client/src/components/home/Abonnement.tsx
  client/src/components/home/PayementPopUp.tsx
  client/src/components/watch/WatchEpisode.tsx
  client/src/pages/Anime.tsx
  client/src/pages/Genre.tsx
  server/package.json
  server/src/modules/user/userRepository.ts
Labels: Add, Fix

#61 FixBug_Abonnement
  client/context/AuthContext.tsx
  client/context/UserContext.tsx
  client/src/components/Footer.tsx
  client/src/components/History/HistoryComponent.tsx
  client/src/components/LogIn.tsx
  client/src/components/Mobile Header/BurgerButton.tsx
  client/src/components/admin/animeManegement/AnimesManagement.tsx
  client/src/components/admin/userManagement/UsersManagement.tsx
  client/src/components/favorite/FavoriteButton.tsx
  client/src/components/genre/PopulaireCarousel.tsx
  client/src/components/genre/SearchCarousel.tsx
  client/src/components/genre/SeinenCarousel.tsx
  client/src/components/genre/ShojoCarousel.tsx
  client/src/components/genre/ShonenCarousel.tsx
  client/src/components/home/Abonnement.tsx
  client/src/components/home/Carousel.tsx
  client/src/components/home/CreateAccount.tsx
  client/src/components/home/PayementPopUp.tsx
  client/src/pages/Favorite.tsx
Labels: bug, Fix

#66 ProfilPicture
  client/context/AuthContext.tsx
  client/context/UserContext.tsx
  client/public/connectedavatar.svg
  client/public/profilpicture2.png
  client/public/profilpicture3.png
  client/public/profilpicture4.png
  client/public/profilpicture5.png
  client/src/components/Header/DesktopNavBar.tsx
  client/src/components/Mobile Header/NavBar.tsx
  client/src/components/account/ProfilePicture.tsx
  client/src/components/admin/userManagement/UsersManagement.tsx
  client/src/components/home/PayementPopUp.tsx
  server/database/schema.sql
  server/src/modules/user/userAction.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
  server/tests/install.test.ts
Labels: Add

#67 Fix_Abonnement_CreateAccount
  client/context/UserContext.tsx
  client/src/components/favorite/FavoriteButton.tsx
  client/src/components/home/Abonnement.tsx
  client/src/components/home/CreateAccount.tsx
  client/src/components/home/PayementPopUp.tsx
  server/src/middleware/checkEmailExists.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: Fix

#68 "Add Feature - Rated Stars"
  client/src/components/Note/Note.tsx
  client/src/components/home/WatchButton.tsx
  client/src/pages/Anime.tsx
  server/database/schema.sql
  server/src/modules/note/noteAction.ts
  server/src/modules/note/noteRepository.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
  server/tests/install.test.ts
Labels: Add
